/**
 * Generates a single API reference page from the OpenAPI spec.
 * Run: bun scripts/generate-docs.ts
 *
 * Reads ../openapi.json and creates a single MDX file at
 * content/docs/api-reference/index.mdx with all operations.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const specPath = resolve(__dirname, "../../openapi.json");
const outputPath = resolve(
  __dirname,
  "../content/docs/api-reference/index.mdx",
);

const spec = JSON.parse(readFileSync(specPath, "utf-8"));

interface Operation {
  path: string;
  method: string;
}

const operations: Operation[] = [];

for (const [path, methods] of Object.entries(spec.paths ?? {})) {
  for (const [method, op] of Object.entries(
    methods as Record<string, unknown>,
  )) {
    if (typeof op !== "object" || op === null) continue;
    operations.push({ path, method });
  }
}

operations.sort(
  (a, b) => a.path.localeCompare(b.path) || a.method.localeCompare(b.method),
);

const opsJson = JSON.stringify(operations);

const mdx = `---
title: API Reference
description: Complete REST API reference for the Agent Swarm platform
full: true
---

{/* This file was generated by scripts/generate-docs.ts. Regenerate with: bun scripts/generate-docs.ts */}

<APIPage document={"../openapi.json"} operations={${opsJson}} />
`;

mkdirSync(resolve(__dirname, "../content/docs/api-reference"), {
  recursive: true,
});
writeFileSync(outputPath, mdx);

console.log(
  `Generated API reference page with ${operations.length} operations`,
);
